/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/portfolio-new.glb --transform 
*/

// @ts-nocheck
import React, { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations, useScroll } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import { useFrame } from '@react-three/fiber'
import * as THREE from 'three'

export function Model(props) {
  const group = React.useRef()
  
  const { scene, animations } = useGLTF('/portfolio30.07.26v4-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)

  const scroll = useScroll()

  useEffect(() => {
    console.log('clips', animations.map(a => a.name), animations.length)
    console.log('actions', Object.keys(actions))
  }, [animations, actions])

  useEffect(() => {
    const animationName = Object.keys(actions)[0]
    if (actions && animationName) {
      actions[animationName].play()
      actions[animationName].paused = true
      actions[animationName].time = 0
    }

    if (materials.PaletteMaterial001) {
      materials.PaletteMaterial001.roughness = 0.1
      materials.PaletteMaterial001.metalness = 0.9
      materials.PaletteMaterial001.color.set("#111111")
      materials.PaletteMaterial001.envMapIntensity = 1.5
    }

    if (nodes['Screen-Inside']?.material) {
      nodes['Screen-Inside'].material.roughness = 0.08
      nodes['Screen-Inside'].material.metalness = 0.85
      nodes['Screen-Inside'].material.color.set('#111111')
      nodes['Screen-Inside'].material.emissive = new THREE.Color('#111111')
      nodes['Screen-Inside'].material.envMapIntensity = 1.5
      nodes['Screen-Inside'].material.transparent = false
      nodes['Screen-Inside'].material.opacity = 1
    }
  }, [actions, materials, nodes])

  // Управляем анимацией персонажа и макбука напрямую через скролл страницы
  // useFrame(() => {
  //   if (actions && scroll) {
  //     Object.values(actions).forEach((action) => {
  //       if (action) {
  //         const duration = action.getClip().duration
  //         action.time = scroll.offset * duration
  //       }
  //     })
  //   }
  // })
  useFrame(() => {
    if (actions && scroll) {
      // scroll.range(нач_позиция, ширина_диапазона)
      // Допустим, у тебя всего 4 страницы (pages={4}):
      // Страница 0 = 0.0, Страница 1 = 0.25, Страница 2 = 0.5, Страница 3 = 0.75
      // Мы хотим, чтобы анимация шла со 2-й страницы (0.5) до 4-й (1.0). 
      // Значит, стартуем с 0.5, а длина диапазона — 0.5.
      
      const animProgress = scroll.range(0.25, 0.75) 

      Object.values(actions).forEach((action) => {
        if (action) {
          const duration = action.getClip().duration
          action.time = animProgress * duration
        }
      })
    }
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0.25]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
        </group>

        <skinnedMesh
          name="model"
          geometry={nodes.model.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.model.skeleton}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
          castShadow
          receiveShadow
        />
      </group>
    </group>
  )
}

useGLTF.preload('/portfolio30.07.26v4-transformed.glb')